/* eslint-disable */
const countries = [
    {name: 'Afganistán' },
{name: 'Albania' },
{name: 'Alemania' },
{name: 'Andorra' },
{name: 'Angola' },
{name: 'Anguilla' },
{name: 'Antártida' },
{name: 'Antigua y Barbuda' },
{name: 'Antillas Holandesas' },
{name: 'Arabia Saudí' },
{name: 'Argelia' },
{name: 'Argentina' },
{name: 'Armenia' },
{name: 'Aruba' },
{name: 'Australia' },
{name: 'Austria' },
{name: 'Azerbaiyán' },
{name: 'Bahamas' },
{name: 'Bahrein' },
{name: 'Bangladesh' },
{name: 'Barbados' },
{name: 'Bélgica' },
{name: 'Belice' },
{name: 'Benin' },
{name: 'Bermudas' },
{name: 'Bielorrusia' },
{name: 'Birmania' },
{name: 'Bolivia' },
{name: 'Bosnia y Herzegovina' },
{name: 'Botswana' },
{name: 'Brasil' },
{name: 'Brunei' },
{name: 'Bulgaria' },
{name: 'Burkina Faso' },
{name: 'Burundi' },
{name: 'Bután' },
{name: 'Cabo Verde' },
{name: 'Camboya' },
{name: 'Camerún' },
{name: 'Canadá' },
{name: 'Chad' },
{name: 'Chile' },
{name: 'China' },
{name: 'Chipre' },
{name: 'Ciudad del Vaticano (Santa Sede)' },
{name: 'Colombia' },
{name: 'Comores' },
{name: 'Congo' },
{name: 'Congo, República Democrática del' },
{name: 'Corea' },
{name: 'Corea del Norte' },
{name: 'Costa de Marfíl' },
{name: 'Costa Rica' },
{name: 'Croacia (Hrvatska)' },
{name: 'Cuba' },
{name: 'Dinamarca' },
{name: 'Djibouti' },
{name: 'Dominica' },
{name: 'Ecuador' },
{name: 'Egipto' },
{name: 'El Salvador' },
{name: 'Emiratos Árabes Unidos' },
{name: 'Eritrea' },
{name: 'Eslovenia' },
{name: 'España' },
{name: 'Estados Unidos' },
{name: 'Estonia' },
{name: 'Etiopía' },
{name: 'Fiji' },
{name: 'Filipinas' },
{name: 'Finlandia' },
{name: 'Francia' },
{name: 'Gabón' },
{name: 'Gambia' },
{name: 'Georgia' },
{name: 'Ghana' },
{name: 'Gibraltar' },
{name: 'Granada' },
{name: 'Grecia' },
{name: 'Groenlandia' },
{name: 'Guadalupe' },
{name: 'Guam' },
{name: 'Guatemala' },
{name: 'Guayana' },
{name: 'Guayana Francesa' },
{name: 'Guinea' },
{name: 'Guinea Ecuatorial' },
{name: 'Guinea-Bissau' },
{name: 'Haití' },
{name: 'Honduras' },
{name: 'Hungría' },
{name: 'India' },
{name: 'Indonesia' },
{name: 'Irak' },
{name: 'Irán' },
{name: 'Irlanda' },
{name: 'Isla Bouvet' },
{name: 'Isla de Christmas' },
{name: 'Islandia' },
{name: 'Islas Caimán' },
{name: 'Islas Cook' },
{name: 'Islas de Cocos o Keeling' },
{name: 'Islas Faroe' },
{name: 'Islas Heard y McDonald' },
{name: 'Islas Malvinas' },
{name: 'Islas Marianas del Norte' },
{name: 'Islas Marshall' },
{name: 'Islas menores de Estados Unidos' },
{name: 'Islas Palau' },
{name: 'Islas Salomón' },
{name: 'Islas Svalbard y Jan Mayen' },
{name: 'Islas Tokelau' },
{name: 'Islas Turks y Caicos' },
{name: 'Islas Vírgenes (EEUU)' },
{name: 'Islas Vírgenes (Reino Unido)' },
{name: 'Islas Wallis y Futuna' },
{name: 'Israel' },
{name: 'Italia' },
{name: 'Jamaica' },
{name: 'Japón' },
{name: 'Jordania' },
{name: 'Kazajistán' },
{name: 'Kenia' },
{name: 'Kirguizistán' },
{name: 'Kiribati' },
{name: 'Kuwait' },
{name: 'Laos' },
{name: 'Lesotho' },
{name: 'Letonia' },
{name: 'Líbano' },
{name: 'Liberia' },
{name: 'Libia' },
{name: 'Liechtenstein' },
{name: 'Lituania' },
{name: 'Luxemburgo' },
{name: 'Macedonia, Ex-República Yugoslava de' },
{name: 'Madagascar' },
{name: 'Malasia' },
{name: 'Malawi' },
{name: 'Maldivas' },
{name: 'Malí' },
{name: 'Malta' },
{name: 'Marruecos' },
{name: 'Martinica' },
{name: 'Mauricio' },
{name: 'Mauritania' },
{name: 'Mayotte' },
{name: 'México' },
{name: 'Micronesia' },
{name: 'Moldavia' },
{name: 'Mónaco' },
{name: 'Mongolia' },
{name: 'Montserrat' },
{name: 'Mozambique' },
{name: 'Namibia' },
{name: 'Nauru' },
{name: 'Nepal' },
{name: 'Nicaragua' },
{name: 'Níger' },
{name: 'Nigeria' },
{name: 'Niue' },
{name: 'Norfolk' },
{name: 'Noruega' },
{name: 'Nueva Caledonia' },
{name: 'Nueva Zelanda' },
{name: 'Omán' },
{name: 'Países Bajos' },
{name: 'Panamá' },
{name: 'Papúa Nueva Guinea' },
{name: 'Paquistán' },
{name: 'Paraguay' },
{name: 'Perú' },
{name: 'Pitcairn' },
{name: 'Polinesia Francesa' },
{name: 'Polonia' },
{name: 'Portugal' },
{name: 'Puerto Rico' },
{name: 'Qatar' },
{name: 'Reino Unido' },
{name: 'República Centroafricana' },
{name: 'República Checa' },
{name: 'República de Sudáfrica' },
{name: 'República Dominicana' },
{name: 'República Eslovaca' },
{name: 'Reunión' },
{name: 'Ruanda' },
{name: 'Rumania' },
{name: 'Rusia' },
{name: 'Sahara Occidental' },
{name: 'Saint Kitts y Nevis' },
{name: 'Samoa' },
{name: 'Samoa Americana' },
{name: 'San Marino' },
{name: 'San Vicente y Granadinas' },
{name: 'Santa Helena' },
{name: 'Santa Lucía' },
{name: 'Santo Tomé y Príncipe' },
{name: 'Senegal' },
{name: 'Seychelles' },
{name: 'Sierra Leona' },
{name: 'Singapur' },
{name: 'Siria' },
{name: 'Somalia' },
{name: 'Sri Lanka' },
{name: 'St Pierre y Miquelon' },
{name: 'Suazilandia' },
{name: 'Sudán' },
{name: 'Suecia' },
{name: 'Suiza' },
{name: 'Surinam' },
{name: 'Tailandia' },
{name: 'Taiwán' },
{name: 'Tanzania' },
{name: 'Tayikistán' },
{name: 'Territorios franceses del Sur' },
{name: 'Timor Oriental' },
{name: 'Togo' },
{name: 'Tonga' },
{name: 'Trinidad y Tobago' },
{name: 'Túnez' },
{name: 'Turkmenistán' },
{name: 'Turquía' },
{name: 'Tuvalu' },
{name: 'Ucrania' },
{name: 'Uganda' },
{name: 'Uruguay' },
{name: 'Uzbekistán' },
{name: 'Vanuatu' },
{name: 'Venezuela' },
{name: 'Vietnam' },
{name: 'Yemen' },
{name: 'Yugoslavia' },
{name: 'Zambia' },
{name: 'Zimbabue' }
  ]
  
  export default {
    countries
  }