/* eslint-disable */
const industries = [
  { name: 'Aeroespacial' },
  { name: 'Agricultura' },
  { name: 'Alimentación' },
  { name: 'Arquitectura' },
  { name: 'Artesanía' },
  { name: 'Banca' },
  { name: 'Coaching' },
  { name: 'Comercio' },
  { name: 'Construcción' },
  { name: 'Consultoría' },
  { name: 'Consumidores' },
  { name: 'Contabilidad' },
  { name: 'Data Science' },
  { name: 'Deportes' },
  { name: 'Derecho' },
  { name: 'Diseño' },
  { name: 'Electrónica' },
  { name: 'Energía' },
  { name: 'Enseñanza' },
  { name: 'Entretenimiento' },
  { name: 'Estatal' },
  { name: 'Exportación' },
  { name: 'Externalización' },
  { name: 'Fabricación' },
  { name: 'Farmaceutica' },
  { name: 'Financiación' },
  { name: 'Finanzas' },
  { name: 'Fitness' },
  { name: 'Fotografía' },
  { name: 'Gubernamental' },
  { name: 'Hostelería' },
  { name: 'Importación' },
  { name: 'Industria' },
  { name: 'Información' },
  { name: 'Ingeniería' },
  { name: 'Inmobiliario' },
  { name: 'Internet' },
  { name: 'Inversiones' },
  { name: 'Investigación' },
  { name: 'Juego' },
  { name: 'Logística' },
  { name: 'Manufactura' },
  { name: 'Marketing' },
  { name: 'Mediación' },
  { name: 'Medicina' },
  { name: 'Mercadis' },
  { name: 'Moda' },
  { name: 'Música' },
  { name: 'Nanotecnología' },
  { name: 'Naval' },
  { name: 'ONG' },
  { name: 'Petróleo' },
  { name: 'Política' },
  { name: 'Producción' },
  { name: 'Protección' },
  { name: 'Psicología' },
  { name: 'Publicidad' },
  { name: 'Reciclaje' },
  { name: 'Reclutamiento' },
  { name: 'Redes' },
  { name: 'Relaciones gubernamentales' },
  { name: 'Religión' },
  { name: 'Reparaciones' },
  { name: 'Sanidad' },
  { name: 'Seguros' },
  { name: 'Selección' },
  { name: 'Servicios' },
  { name: 'Software' },
  { name: 'Tecnología' },
  { name: 'Textil' },
  { name: 'Traducción' },
  { name: 'Transporte' },
  { name: 'Turismo' },
  { name: 'Ventas' },
  { name: 'Viajes' },
  { name: 'Video' },
  { name: 'Otra' }
]

export default {
  industries
}